services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gazette
    ports:
      - "5432:5432"
    volumes:
      - gazette_pg:/var/lib/postgresql/data

volumes:
  gazette_pg:
